Tr 68
nazariykupchenko/api-tests pull request #3
Opened 2022-02-21 19:30 UTC by nazariykupchenko

2022-02-21 19:42 UTC, nazariykupchenko reviewed
Should get rid of .idea folder with its files

2022-02-21 21:34 UTC, adzombak commented on src/main/java/com/api/endpoints/reqres/ReqresUserEndpoint.java
> +  public ValidatableResponse getSingleUser(int i) {
change variable name to id to be more clear about it

2022-02-21 21:36 UTC, adzombak commented on src/main/java/com/api/endpoints/swapi/SwapiUserEndpoint.java
> +  public ValidatableResponse getUser(int i) {
swapi doesn't have users, update respectively

2022-02-21 21:37 UTC, adzombak commented on src/main/java/com/api/models/reqres/ListOfResourcesModel.java
> +
remove unnecessary lines

2022-02-21 21:38 UTC, adzombak commented on src/main/java/com/api/models/reqres/SingleResourceModel.java
> +
and here

2022-02-21 21:40 UTC, adzombak requested changes
update code formatting and remove idea files from git

2022-02-22 08:34 UTC, adzombak commented on src/main/java/com/api/models/reqres/ListOfResourcesModel.java
> +
@nazariykupchenko in all models after the last variable and '}' all lines should be removed

2022-02-22 08:46 UTC, adzombak commented on src/main/java/com/api/endpoints/Api.java
> +
this line should be removed

2022-02-22 08:46 UTC, adzombak commented on src/main/java/com/api/models/reqres/CreateUserModel.java
> +
this line should be removed

2022-02-22 08:46 UTC, adzombak commented on src/main/java/com/api/models/reqres/ListOfUsersModel.java
> +
this line should be removed

2022-02-22 08:46 UTC, adzombak commented on src/main/java/com/api/models/reqres/SingleResourceModel.java
> +
this line should be removed

2022-02-22 08:46 UTC, adzombak commented on src/main/java/com/api/models/reqres/SingleUserModel.java
> +
this line should be removed

2022-02-22 08:46 UTC, adzombak commented on src/main/java/com/api/models/reqres/UpdateUserModel.java
> +
this line should be removed

2022-02-22 08:56 UTC, nazariykupchenko commented on src/main/java/com/api/models/reqres/CreateUserModel.java
> +
@adzombak , а чому createAt видаляти?

2022-02-22 08:58 UTC, adzombak commented on src/main/java/com/api/models/reqres/SingleUserModel.java
> +  private String avatar; //тут ссилка на img
don't leave such comments

2022-02-22 08:59 UTC, adzombak commented on src/main/java/com/api/endpoints/Api.java
> +
this line is not removed

2022-02-22 10:00 UTC, adzombak approved these changes

2022-02-22 10:02 UTC, merged